---
title: "Overview"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(dplyr)
ds <- read_csv("ds.csv") %>% 
  mutate(date = as.Date(RecordedDate, format = "%d/%m/%Y"), 
         nps = if_else(Q13 <=6, -100,
                       if_else(Q13 >=9, 100, 0)),
         miss_most = Q14,
         ma =  Q6_1, esg = Q6_2, trade = Q6_3, climate = Q6_4, energy = Q6_5, tech_asia = Q6_6, sport = Q6_7,
         new_subj = Q7) %>% 
  select(date, nps, miss_most, ma, esg, trade, climate, energy, tech_asia, sport, new_subj) 
```

```{r}
library(lubridate)
ds %>% 
  mutate(month = floor_date(date, "month")) %>% 
  group_by(month) %>% 
  summarise(nps = mean(nps, na.rm = T),
            n = n())
```

```{r}
library(tidytext)
library(tidyr)
library(ggrepel)
library(tm)

ds %>% 
  drop_na() %>% 
  unnest_tokens(word, miss_most) %>% 
  anti_join(stop_words) %>% 
  mutate(word = stemDocument(word)) %>% 
  group_by(word) %>% 
  summarise(n = n(), 
            nps = mean(nps)) %>% 
  arrange(-n) %>% 
  filter(!word %in% c("ft")) %>% 
  filter(n >= 20) %>% 
  ggplot(aes(n, nps, label = word)) +
  geom_text_repel() +
  scale_x_log10() +
  theme_minimal() +
  labs(x = "\nNumber of susbcribers who mention this",
       y = "NPS\n")
```


```{r}
library(stringr)
ds %>% 
  select(ma, esg, climate, energy, tech_asia, sport) %>% 
  drop_na() %>% 
  mutate(across(everything(), ~ na_if(., "I'm not interested in this content"))) %>% 
  mutate(across(everything(), ~ as.numeric(factor(., levels = c("Not very useful", 
                                                     "Slightly useful", 
                                                     "Moderately useful", 
                                                     "Very useful", 
                                                     "Extremely useful"))))) %>% 
  cor(method = "kendall", use = "complete.obs")
```

```{r}
ds %>% 
  select(ma, esg, climate, energy, tech_asia, sport, new_subj) %>% 
  drop_na() %>% 
  pivot_longer(1:6) %>% 
  filter(value %in% c("Very useful", "Extremely useful")) %>% 
  unnest_tokens("word", new_subj) %>% 
  anti_join(stop_words) %>% 
  mutate(word = stemDocument(word)) %>% 
  group_by(name, word) %>% 
  summarise(n = n()) %>% 
  arrange(-n) %>% 
  group_by(name) %>% 
  filter(!word %in% c("coverag", "ft", "news", "analysi")) %>% 
  top_n(5, wt = n) %>% 
  ggplot(aes(reorder(word, - n), n)) +
  geom_col() +
  facet_wrap(~name, scales = "free") +
  coord_flip()
```